alter table developments
  add column if not exists listing_duration      text,
  add column if not exists developer_website     text,
  add column if not exists logo_url              text,
  add column if not exists street_address        text,
  add column if not exists street_address_2      text,
  add column if not exists country               text,
  add column if not exists city                  text,
  add column if not exists postcode              text,
  add column if not exists location_description  text,
  add column if not exists sale_office_street    text,
  add column if not exists sale_office_street_2  text,
  add column if not exists sale_office_country   text,
  add column if not exists sale_office_state     text,
  add column if not exists sale_office_city      text,
  add column if not exists sale_office_postcode  text,
  add column if not exists display_suite_timing  text,
  add column if not exists description           text,
  add column if not exists search_price_max      bigint,
  add column if not exists show_price_on_search  boolean DEFAULT true,
  add column if not exists promotional_banner    text,
  add column if not exists configuration_label   text;
